# 配置文件版本
version: 5.1.0

# 主题变体，可以是 default 或 cyberpunk
variant: default

# Logo
logo:
  text: Hexo for OIers

# 页面元数据配置
head:
  # 网站图标的 URL 或路径
  favicon: https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg

  # Web App 配置
  # https://developer.mozilla.org/en-US/docs/Web/Manifest
  manifest:
    # Name of the web application (default to the site title)
    name:
    # The displayed name of the web application
    # when there is not enough space to display full name
    short_name:
    # The start URL of the web application
    start_url:
    # The default theme color for the application
    theme_color:
    # A placeholder background color for the application page to display
    # before its stylesheet is loaded
    background_color:
    # The preferred display mode for the website
    display: standalone
    # Image files that can serve as application icons for different contexts
    icons:
      - # The path to the image file
        src: ""
        # A string containing space-separated image dimensions
        sizes: ""
        # A hint as to the media type of the image
        type:

  # Open Graph 元数据
  # https://hexo.io/docs/helpers.html#open-graph
  open_graph:
    # Page title (og:title) (optional)
    # You should leave this blank for most of the time
    title:
    # Page type (og:type) (optional)
    # You should leave this blank for most of the time
    type: blog
    # Page URL (og:url) (optional)
    # You should leave this blank for most of the time
    url:
    # Page cover (og:image) (optional)
    # You should leave this blank for most of the time
    image:
    # Site name (og:site_name) (optional)
    # You should leave this blank for most of the time
    site_name:
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    author:
    # Page description (og:description) (optional)
    # You should leave this blank for most of the time
    description:
    # Twitter card type (twitter:card)
    twitter_card:
    # Twitter ID (twitter:creator)
    twitter_id:
    # Twitter Site (twitter:site)
    twitter_site:
    # Google+ profile link (deprecated)
    google_plus:
    # Facebook admin ID
    fb_admins:
    # Facebook App ID
    fb_app_id:

  # Structured data of the page
  # https://developers.google.com/search/docs/guides/intro-structured-data
  structured_data:
    # Page title (optional)
    # You should leave this blank for most of the time
    title:
    # Page description (optional)
    # You should leave this blank for most of the time
    description:
    # Page URL (optional)
    # You should leave this blank for most of the time
    url:
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    author:
    # Page publisher (optional)
    # You should leave this blank for most of the time
    publisher:
    # Page publisher logo (optional)
    # You should leave this blank for most of the time
    publisher_logo:
    # Page images (optional)
    # You should leave this blank for most of the time
    image:

  # Additional HTML meta tags in an array
  meta:
    # Meta tag specified in <attribute>=<value> style
    # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
    - ""
  # URL or path to the website's RSS atom.xml
  rss:

# 页面顶栏配置
navbar:
  # 导航菜单项
  menu:
    首页: /
    归档: /archives
    分类: /categories
    标签: /tags
    关于: /about
  # 要显示在导航栏右侧的链接
  links:

# 页脚配置
footer:
  # 显示在页脚部分右侧的链接
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: "https://creativecommons.org/licenses/by/4.0/"
    Download on GitHub:
      icon: fab fa-github
      url: "https://github.com/renbaoshuo/hexo-for-oiers"

# 文章相关配置
article:
  # 代码高亮设置
  highlight:
    # 代码高亮主题
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: atom-one-light
    # 显示「复制代码」按钮
    clipboard: true
    # 代码块的默认折叠状态
    # 可以是 "", "folded", "unfolded"
    fold: unfolded
  # 是否显示预计文章阅读时间
  # 编者注：在 OI 相关的博文中并不准确，故默认禁用
  readtime: false
  # 是否显示更新时间。
  # 对于 `auto` ，仅当设置了 `page.updated` 且其值不同于 `page.date` 时才显示文章更新时间
  update_time: true
  # 文章尾部版权协议提示
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    Attribution:
      icon: fab fa-creative-commons-by
      url: "https://creativecommons.org/licenses/by/4.0/"
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: "https://creativecommons.org/licenses/by-nc/4.0/"

# 搜索配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
  type: insight

# 评论配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
  - type:

# 捐赠配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:

# 分享配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
  type:

# 侧栏配置
# 请注意，侧边栏只有在至少有一个小部件时才可见
sidebar:
  # 左侧边栏配置
  left:
    # 页面滚动时侧边栏是否固定在顶部
    sticky: false
  # 右侧边栏配置
  right:
    # 页面滚动时侧边栏是否固定在顶部
    sticky: false

# 侧栏小部件配置
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
  # 个人资料卡片
  - # 组件放置位置
    position: left
    type: profile
    # 作者
    author: Hexo for OIers
    # Author title
    author_title:
    # 位置
    location: localhost
    # 头像
    avatar: https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg
    # 是否使用圆形头像
    avatar_rounded: false
    # Gravatar 邮箱地址
    gravatar:
    # 「关注我」按钮的链接
    follow_link: https://github.com/renbaoshuo
    # 社交按钮
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/renbaoshuo/hexo-for-oiers
      RSS:
        icon: fas fa-rss
        url: /atom.xml
  # 文章目录
  - position: left
    type: toc
    # 是否显示每个标题的索引
    index: true
    # 子标题在视野外时是否折叠
    collapsed: true
    # 要显示的最大标题级别 (1-6)
    depth: 3
  # 推荐链接
  - position: left
    type: links
    # 链接的名称和指向
    links:
      Hexo: https://hexo.io
      Bulma: https://bulma.io
      Baoshuo: https://baoshuo.ren
      Hexo for OIers: https://github.com/renbaoshuo/hexo-for-oiers
  # 分类
  - position: left
    type: categories
  # 最新文章
  - position: left
    type: recent_posts
  # 归档
  - position: left
    type: archives
  # 标签
  - position: left
    type: tags

# 插件
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
  # 启用页面启动动画
  animejs: true
  # 显示「返回顶部」按钮
  back_to_top: true
  # 百度统计
  # https://tongji.baidu.com
  baidu_analytics:
    # 百度统计跟踪 ID
    tracking_id:
  # 必应网站管理员工具
  # https://www.bing.com/toolbox/webmaster/
  bing_webmaster:
    # 跟踪 ID
    tracking_id:
  # 不蒜子
  # https://busuanzi.ibruce.info
  busuanzi: false
  # CNZZ 统计
  # https://www.umeng.com/web
  cnzz:
    # CNZZ 跟踪 ID
    id:
    # CNZZ 站点 ID
    web_id:
  # 谷歌统计
  # https://analytics.google.com
  google_analytics:
    # 跟踪 ID
    tracking_id:
  # 提醒用户使用 cookie
  # https://www.osano.com/cookieconsent/
  cookie_consent:
    ## The compliance type. Can be "info", "opt-in", or "opt-out"
    # type: info
    ## Theme of the popup. Can be "block", "edgeless", or "classic"
    # theme: edgeless
    ## Whether the popup should stay static regardless of the page scrolls
    # static: false
    ## Where on the screen the consent popup should display
    # position: bottom-left
    ## URL to your site's cookie policy
    # policyLink: "https://www.cookiesandyou.com/"
  # 启用 lightGallery 和 Justified Gallery 插件
  gallery: true
  # Hotjar 用户反馈插件
  # https://www.hotjar.com/
  hotjar:
    # Hotjar site id
    site_id:
  # 启用 KaTeX 数学公式支持
  # https://katex.org/
  katex: false
  # 启用 MathJax 数学公式支持
  # https://www.mathjax.org/
  mathjax: true
  # 开启 Outdated Browser 插件
  # http://outdatedbrowser.com/
  outdated_browser: false
  # 页面加载时在顶部显示进度条
  progressbar: true
  # Statcounter statistics
  # https://statcounter.com/
  statcounter:
    # Statcounter project id
    project:
    # Statcounter project security code
    security:
  # Twitter conversion tracking plugin settings
  # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
  twitter_conversion_tracking:
    # Twitter Pixel ID
    pixel_id:

# CDN 配置
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  # Name or URL template of the JavaScript and/or stylesheet CDN provider
  cdn: loli
  # Name or URL template of the webfont CDN provider
  fontcdn: loli
  # Name or URL of the fontawesome icon font CDN provider
  iconcdn: loli
